SELECT TAXON_DEFINITION_ID
FROM TAXONOMY_REGISTRY
WHERE CLASSIFICATION_ID = :classificationId AND PATH <@
		(SELECT PATH
			FROM TAXONOMY_REGISTRY
			WHERE TAXON_DEFINITION_ID = :taxonId AND CLASSIFICATION_ID = :classificationId)